# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [2]:
import pandas as pd
import numpy as np

## Load the data

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,1,7,0,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8
10,1,0,0,1,7,0,260,50,36,239.554,23,0,4,0,8
11,1,0,0,1,7,1,260,50,36,239.554,23,0,4,0,8
12,1,0,0,1,7,2,260,50,36,239.554,23,0,4,0,8
13,1,0,0,1,7,2,179,51,38,239.554,31,0,0,0,1
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,4
15,1,0,0,1,7,4,246,25,41,239.554,23,0,0,0,8
16,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2
17,0,0,1,1,7,0,179,51,38,239.554,31,0,0,0,8
18,1,0,0,1,7,3,189,29,33,239.554,25,0,2,2,8
19,0,0,0,1,8,2,248,25,47,205.917,32,0,2,1,2

## Create the targets( 1's and 0's instead of number of hours)

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

We will create the targets as follow:

0 stand for moderatly absent, where Absenteeism time is less than or equal to 3 hours

1 stand for excessively absent, where Absenteeism time is greater than or equal 4 hours

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

np.unique(targets)

array([0, 1])

In [6]:
targets.shape

(700,)

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

### Cheking for balance

In [8]:
number_of_ones = targets.sum()
total_number_of_elements = targets.shape[0]

Balance_check = number_of_ones / total_number_of_elements
Balance_check

0.45571428571428574

45% is acceptable, the data is balanced

### drop the 'Absenteeism Time in Hours' from the dataset

In [9]:
#after we see the result in the summary table we came back to this cell and drop the non-important features

data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work','Reason_4'],axis=1)

data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,7,289,33,30,0,2,1,1
1,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,7,179,38,31,0,0,0,0
3,1,0,0,7,279,39,24,0,2,0,1
4,0,0,0,7,289,33,30,0,2,1,0

# Select the inputs for the regression

In [10]:
data_with_targets.shape

(700, 11)

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

,Reason_1,Reason_2,Reason_3,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,7,289,33,30,0,2,1
1,0,0,0,7,118,50,31,0,1,0
2,0,0,0,7,179,38,31,0,0,0
3,1,0,0,7,279,39,24,0,2,0
4,0,0,0,7,289,33,30,0,2,1

# Standardize the data

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler


class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [13]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [14]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Education']

In [15]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [16]:
absenteeism_scaler = CustomScaler(columns = columns_to_scale)

In [17]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [18]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

,Reason_1,Reason_2,Reason_3,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [19]:
scaled_inputs.shape

(700, 10)

## Split the data into train & test and shuffle

### Import the relevant module

In [20]:
from sklearn.model_selection import train_test_split

### Split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [22]:
print (x_train.shape, y_train.shape)

(560, 10) (560,)

In [23]:
print (x_test.shape, y_test.shape)

(140, 10) (140,)

# Logistic regression with sklearn

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [25]:
reg = LogisticRegression()

In [26]:
reg.fit(x_train,y_train)

LogisticRegression()

In [27]:
reg.score(x_train,y_train)

0.7589285714285714

we got 76% accuracy on our train data

### Finding the intercept and coefficients

In [28]:
reg.intercept_

array([-0.89430347])

In [29]:
reg.coef_

array([[ 2.07829536,  0.56483534,  2.46124051,  0.14594384,  0.58473439,
        -0.19183695,  0.2830851 , -0.24881378,  0.33608699, -0.27816207]])

### Creating a summary table

In [30]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [31]:
feature_name = unscaled_inputs.columns.values

In [32]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

             Feature name  Coefficient
0                Reason_1     2.078295
1                Reason_2     0.564835
2                Reason_3     2.461241
3             Month Value     0.145944
4  Transportation Expense     0.584734
5                     Age    -0.191837
6         Body Mass Index     0.283085
7               Education    -0.248814
8                Children     0.336087
9                    Pets    -0.278162

a feature is not particularly important if it's coefficient is around 0

## Testing the model

In [33]:
reg.score(x_test,y_test)

0.7142857142857143

In [34]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.72950466, 0.27049534],
       [0.61849096, 0.38150904],
       [0.47002668, 0.52997332],
       [0.79008837, 0.20991163],
       [0.08538205, 0.91461795],
       [0.32020341, 0.67979659],
       [0.29191653, 0.70808347],
       [0.12475811, 0.87524189],
       [0.79299087, 0.20700913],
       [0.76111179, 0.23888821],
       [0.52181134, 0.47818866],
       [0.24765854, 0.75234146],
       [0.0672757 , 0.9327243 ],
       [0.75389786, 0.24610214],
       [0.30651775, 0.69348225],
       [0.57412812, 0.42587188],
       [0.57337703, 0.42662297],
       [0.5631545 , 0.4368455 ],
       [0.41334168, 0.58665832],
       [0.05062227, 0.94937773],
       [0.71633717, 0.28366283],
       [0.79008837, 0.20991163],
       [0.40654623, 0.59345377],
       [0.40654623, 0.59345377],
       [0.22388   , 0.77612   ],
       [0.75670646, 0.24329354],
       [0.54184086, 0.45815914],
       [0.86789731, 0.13210269],
       [0.18707494, 0.81292506],
       [0.79008837, 0.20991163],
       [0.65697027, 0.34302973],
       [0.30606445, 0.69393555],
       [0.3023412 , 0.6976588 ],
       [0.50099098, 0.49900902],
       [0.79008837, 0.20991163],
       [0.48663058, 0.51336942],
       [0.78606721, 0.21393279],
       [0.23751735, 0.76248265],
       [0.62553688, 0.37446312],
       [0.42725116, 0.57274884],
       [0.79691552, 0.20308448],
       [0.53433233, 0.46566767],
       [0.77171907, 0.22828093],
       [0.42725116, 0.57274884],
       [0.17659095, 0.82340905],
       [0.39463757, 0.60536243],
       [0.29593502, 0.70406498],
       [0.72950466, 0.27049534],
       [0.79530165, 0.20469835],
       [0.80357582, 0.19642418],
       [0.42047914, 0.57952086],
       [0.50175877, 0.49824123],
       [0.32020341, 0.67979659],
       [0.7516018 , 0.2483982 ],
       [0.16866093, 0.83133907],
       [0.59864229, 0.40135771],
       [0.10679269, 0.89320731],
       [0.77785901, 0.22214099],
       [0.49082593, 0.50917407],
       [0.48041782, 0.51958218],
       [0.29680006, 0.70319994],
       [0.32934064, 0.67065936],
       [0.72343286, 0.27656714],
       [0.18976482, 0.81023518],
       [0.8022701 , 0.1977299 ],
       [0.74563154, 0.25436846],
       [0.82582192, 0.17417808],
       [0.78606721, 0.21393279],
       [0.2489806 , 0.7510194 ],
       [0.72168528, 0.27831472],
       [0.78606721, 0.21393279],
       [0.55603634, 0.44396366],
       [0.09621546, 0.90378454],
       [0.57560937, 0.42439063],
       [0.42470188, 0.57529812],
       [0.79008837, 0.20991163],
       [0.20683262, 0.79316738],
       [0.26885226, 0.73114774],
       [0.25836984, 0.74163016],
       [0.34482916, 0.65517084],
       [0.76429542, 0.23570458],
       [0.85268193, 0.14731807],
       [0.77785901, 0.22214099],
       [0.24013661, 0.75986339],
       [0.59867852, 0.40132148],
       [0.88586347, 0.11413653],
       [0.28505758, 0.71494242],
       [0.40654623, 0.59345377],
       [0.60861153, 0.39138847],
       [0.30606445, 0.69393555],
       [0.84165325, 0.15834675],
       [0.85611256, 0.14388744],
       [0.78309419, 0.21690581],
       [0.74563154, 0.25436846],
       [0.76111179, 0.23888821],
       [0.14882255, 0.85117745],
       [0.72120415, 0.27879585],
       [0.23146133, 0.76853867],
       [0.77419969, 0.22580031],
       [0.80542782, 0.19457218],
       [0.40447878, 0.59552122],
       [0.30606445, 0.69393555],
       [0.30024813, 0.69975187],
       [0.25522729, 0.74477271],
       [0.58575483, 0.41424517],
       [0.55513441, 0.44486559],
       [0.73764794, 0.26235206],
       [0.14882255, 0.85117745],
       [0.22292718, 0.77707282],
       [0.86116966, 0.13883034],
       [0.86284571, 0.13715429],
       [0.09476529, 0.90523471],
       [0.30542354, 0.69457646],
       [0.68456412, 0.31543588],
       [0.49704453, 0.50295547],
       [0.46844161, 0.53155839],
       [0.19523449, 0.80476551],
       [0.17894524, 0.82105476],
       [0.45078548, 0.54921452],
       [0.70779445, 0.29220555],
       [0.7534534 , 0.2465466 ],
       [0.85289484, 0.14710516],
       [0.21090459, 0.78909541],
       [0.53433233, 0.46566767],
       [0.79008837, 0.20991163],
       [0.6779779 , 0.3220221 ],
       [0.79691552, 0.20308448],
       [0.89251747, 0.10748253],
       [0.25233745, 0.74766255],
       [0.71633717, 0.28366283],
       [0.41708687, 0.58291313],
       [0.79691552, 0.20308448],
       [0.72120415, 0.27879585],
       [0.6779779 , 0.3220221 ],
       [0.74773327, 0.25226673],
       [0.49704453, 0.50295547],
       [0.5631545 , 0.4368455 ],
       [0.71323915, 0.28676085],
       [0.77419969, 0.22580031],
       [0.57560937, 0.42439063]])

In [35]:
predicted_proba.shape

(140, 2)

predicted_proba[0] is the probability of 0 / not excessively absent

predicted_proba[1] is the probability of 1 / excessively absent

In [36]:
x_test_probability_of_excessively_absent = predicted_proba[:,1]
x_test_probability_of_excessively_absent

array([0.27049534, 0.38150904, 0.52997332, 0.20991163, 0.91461795,
       0.67979659, 0.70808347, 0.87524189, 0.20700913, 0.23888821,
       0.47818866, 0.75234146, 0.9327243 , 0.24610214, 0.69348225,
       0.42587188, 0.42662297, 0.4368455 , 0.58665832, 0.94937773,
       0.28366283, 0.20991163, 0.59345377, 0.59345377, 0.77612   ,
       0.24329354, 0.45815914, 0.13210269, 0.81292506, 0.20991163,
       0.34302973, 0.69393555, 0.6976588 , 0.49900902, 0.20991163,
       0.51336942, 0.21393279, 0.76248265, 0.37446312, 0.57274884,
       0.20308448, 0.46566767, 0.22828093, 0.57274884, 0.82340905,
       0.60536243, 0.70406498, 0.27049534, 0.20469835, 0.19642418,
       0.57952086, 0.49824123, 0.67979659, 0.2483982 , 0.83133907,
       0.40135771, 0.89320731, 0.22214099, 0.50917407, 0.51958218,
       0.70319994, 0.67065936, 0.27656714, 0.81023518, 0.1977299 ,
       0.25436846, 0.17417808, 0.21393279, 0.7510194 , 0.27831472,
       0.21393279, 0.44396366, 0.90378454, 0.42439063, 0.57529812,
       0.20991163, 0.79316738, 0.73114774, 0.74163016, 0.65517084,
       0.23570458, 0.14731807, 0.22214099, 0.75986339, 0.40132148,
       0.11413653, 0.71494242, 0.59345377, 0.39138847, 0.69393555,
       0.15834675, 0.14388744, 0.21690581, 0.25436846, 0.23888821,
       0.85117745, 0.27879585, 0.76853867, 0.22580031, 0.19457218,
       0.59552122, 0.69393555, 0.69975187, 0.74477271, 0.41424517,
       0.44486559, 0.26235206, 0.85117745, 0.77707282, 0.13883034,
       0.13715429, 0.90523471, 0.69457646, 0.31543588, 0.50295547,
       0.53155839, 0.80476551, 0.82105476, 0.54921452, 0.29220555,
       0.2465466 , 0.14710516, 0.78909541, 0.46566767, 0.20991163,
       0.3220221 , 0.20308448, 0.10748253, 0.74766255, 0.28366283,
       0.58291313, 0.20308448, 0.27879585, 0.3220221 , 0.25226673,
       0.50295547, 0.4368455 , 0.28676085, 0.22580031, 0.42439063])

In [37]:
x_test_probability_of_excessively_absent.shape

(140,)

### Preparing a *.csv file that contain data with predictions

In [40]:
data_to_load_in_tableau = unscaled_inputs.copy()
data_to_load_in_tableau

,Reason_1,Reason_2,Reason_3,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,7,289,33,30,0,2,1
1,0,0,0,7,118,50,31,0,1,0
2,0,0,0,7,179,38,31,0,0,0
3,1,0,0,7,279,39,24,0,2,0
4,0,0,0,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,5,179,40,22,1,2,0
696,1,0,0,5,225,28,24,0,1,2
697,1,0,0,5,330,28,25,1,0,0
698,0,0,0,5,235,32,25,1,0,0
699,0,0,0,5,291,40,25,0,1,1

In [42]:
predicitons = reg.predict_proba(scaled_inputs)
Probability_of_excessivly_absent = predicitons[:, 1]
Probability_of_excessivly_absent

array([0.56508671, 0.14731807, 0.23888821, 0.87107976, 0.56508671,
       0.23888821, 0.45744381, 0.57274884, 0.80476551, 0.27831472,
       0.91461795, 0.91461795, 0.91461795, 0.71494242, 0.23888821,
       0.70843286, 0.23888821, 0.78624803, 0.70808347, 0.41424517,
       0.87503771, 0.72335785, 0.87537315, 0.58291313, 0.94074051,
       0.46780232, 0.57529812, 0.16251436, 0.94074051, 0.2465466 ,
       0.79316738, 0.68553551, 0.28676085, 0.68553551, 0.2465466 ,
       0.46780232, 0.57529812, 0.83165286, 0.15684254, 0.58291313,
       0.20324872, 0.14388744, 0.25436846, 0.92399734, 0.27656714,
       0.14388744, 0.25436846, 0.38150904, 0.59300745, 0.83133907,
       0.59300745, 0.26703827, 0.26703827, 0.14388744, 0.58544566,
       0.15809704, 0.81023518, 0.25436846, 0.78909541, 0.42439063,
       0.25436846, 0.59300745, 0.26235206, 0.14909687, 0.16372253,
       0.1369537 , 0.26235206, 0.27527272, 0.14909687, 0.27527272,
       0.43460021, 0.39138847, 0.26235206, 0.27527272, 0.94681468,
       0.83710119, 0.27527272, 0.59552122, 0.48859389, 0.60302383,
       0.27049534, 0.28366283, 0.74766255, 0.76236243, 0.40135771,
       0.76853867, 0.26395208, 0.84270371, 0.28366283, 0.76853867,
       0.28366283, 0.76236243, 0.75986339, 0.61295461, 0.44486559,
       0.28366283, 0.92461726, 0.40135771, 0.45517823, 0.69058919,
       0.1754548 , 0.3220221 , 0.29220555, 0.62279235, 0.69058919,
       0.509425  , 0.29220555, 0.62279235, 0.29220555, 0.509425  ,
       0.15998156, 0.8144324 , 0.29220555, 0.20700913, 0.58528872,
       0.10748253, 0.76248265, 0.20700913, 0.15453588, 0.20700913,
       0.20700913, 0.10748253, 0.20700913, 0.10748253, 0.10748253,
       0.10748253, 0.10748253, 0.10748253, 0.10748253, 0.56104381,
       0.92223169, 0.10748253, 0.15453588, 0.10748253, 0.10748253,
       0.20700913, 0.50295547, 0.16005875, 0.66361435, 0.67065936,
       0.22214099, 0.1977299 , 0.52117063, 0.51336942, 0.84918193,
       0.84918193, 0.21393279, 0.21393279, 0.10209388, 0.16005875,
       0.21393279, 0.88886401, 0.40563235, 0.21393279, 0.74282375,
       0.33419983, 0.930062  , 0.64868426, 0.25653108, 0.324502  ,
       0.90067051, 0.48645108, 0.82105476, 0.90067051, 0.6104925 ,
       0.70406498, 0.53155839, 0.70406498, 0.89784023, 0.6104925 ,
       0.53155839, 0.22102348, 0.85117745, 0.67979659, 0.22102348,
       0.69393555, 0.48645108, 0.69393555, 0.69393555, 0.67979659,
       0.85117745, 0.22102348, 0.82105476, 0.22102348, 0.33370168,
       0.22828093, 0.23687375, 0.68195694, 0.23687375, 0.22828093,
       0.54191887, 0.68879795, 0.13229726, 0.33370168, 0.68195694,
       0.33370168, 0.37446312, 0.9327243 , 0.93073712, 0.71267247,
       0.8784415 , 0.90159933, 0.73114774, 0.13603912, 0.90523471,
       0.24448831, 0.24448831, 0.7719085 , 0.78327683, 0.63309316,
       0.24448831, 0.6976588 , 0.90523471, 0.43755459, 0.4360901 ,
       0.39130775, 0.44396366, 0.6976588 , 0.5595081 , 0.4368455 ,
       0.77365431, 0.44712197, 0.69975187, 0.35248058, 0.69975187,
       0.70637492, 0.25226673, 0.69975187, 0.56975077, 0.7472106 ,
       0.14216042, 0.56975077, 0.40127629, 0.70637492, 0.3306267 ,
       0.24329354, 0.80476551, 0.57993408, 0.55270054, 0.13392317,
       0.45668168, 0.62138003, 0.26020739, 0.87040976, 0.87040976,
       0.15692259, 0.45744381, 0.56508671, 0.23888821, 0.93837448,
       0.93837448, 0.57274884, 0.94074051, 0.69457646, 0.57529812,
       0.71939351, 0.86353981, 0.86353981, 0.58291313, 0.57529812,
       0.41424517, 0.77707282, 0.12739814, 0.59004979, 0.41424517,
       0.28676085, 0.15262956, 0.82492418, 0.87537315, 0.66161843,
       0.73161809, 0.25436846, 0.94302122, 0.50917407, 0.72534304,
       0.38150904, 0.43708632, 0.39192208, 0.73161809, 0.72534304,
       0.25436846, 0.38150904, 0.59300745, 0.50917407, 0.15809704,
       0.50917407, 0.38150904, 0.83133907, 0.73161809, 0.59552122,
       0.30410382, 0.59552122, 0.59552122, 0.16372253, 0.43460021,
       0.55909006, 0.58336275, 0.79594651, 0.26235206, 0.55909006,
       0.51958218, 0.94521926, 0.60302383, 0.51958218, 0.51958218,
       0.51958218, 0.16372253, 0.39138847, 0.1369537 , 0.16372253,
       0.88418406, 0.60302383, 0.39138847, 0.17417808, 0.55909006,
       0.55909006, 0.16372253, 0.59345377, 0.44486559, 0.74766255,
       0.61295461, 0.40135771, 0.86835451, 0.76853867, 0.52997332,
       0.49824123, 0.84225162, 0.59345377, 0.31299316, 0.27049534,
       0.74163016, 0.84270371, 0.74163016, 0.27049534, 0.9267662 ,
       0.73586459, 0.45219448, 0.49972947, 0.27049534, 0.76738414,
       0.27879585, 0.27879585, 0.3220221 , 0.1754548 , 0.62279235,
       0.74953373, 0.27879585, 0.27879585, 0.14710516, 0.15998156,
       0.3220221 , 0.27879585, 0.90378454, 0.79146864, 0.62279235,
       0.18649251, 0.27879585, 0.94937773, 0.20700913, 0.58528872,
       0.21502435, 0.70587811, 0.21502435, 0.50295547, 0.77933582,
       0.42637737, 0.11859498, 0.19642418, 0.19642418, 0.11154565,
       0.20308448, 0.68501484, 0.51336942, 0.52117063, 0.20308448,
       0.20308448, 0.20308448, 0.67065936, 0.19799828, 0.20308448,
       0.1977299 , 0.20308448, 0.19799828, 0.31543588, 0.54702242,
       0.20308448, 0.20308448, 0.66361435, 0.20308448, 0.20308448,
       0.60536243, 0.7510194 , 0.20469835, 0.53155839, 0.20991163,
       0.24610214, 0.1639794 , 0.37164755, 0.20991163, 0.41646275,
       0.74449629, 0.79277434, 0.1275868 , 0.53887864, 0.53887864,
       0.24610214, 0.20469835, 0.1275868 , 0.20991163, 0.52377177,
       0.930062  , 0.20469835, 0.21690581, 0.54191887, 0.42587188,
       0.75234146, 0.37446312, 0.42587188, 0.21690581, 0.13229726,
       0.54921452, 0.40132148, 0.54191887, 0.21690581, 0.52163219,
       0.87526357, 0.38427344, 0.96198811, 0.11413653, 0.22406695,
       0.4368455 , 0.55224323, 0.63011722, 0.63011722, 0.69348225,
       0.23570458, 0.86071602, 0.11413653, 0.12454854, 0.73925923,
       0.11413653, 0.12916344, 0.23139465, 0.12916344, 0.24329354,
       0.56252274, 0.23139465, 0.81307898, 0.23139465, 0.22580031,
       0.23139465, 0.47793812, 0.23139465, 0.24329354, 0.14216042,
       0.70637492, 0.61152843, 0.22580031, 0.86563672, 0.7472106 ,
       0.12283742, 0.25104657, 0.91461795, 0.76977134, 0.45668168,
       0.13392317, 0.57274884, 0.13392317, 0.57196642, 0.15141064,
       0.23316767, 0.72815008, 0.23888821, 0.14731807, 0.45744381,
       0.56508671, 0.488343  , 0.23316767, 0.36204832, 0.45815914,
       0.2465466 , 0.19457218, 0.24070067, 0.13883034, 0.57529812,
       0.498758  , 0.37172668, 0.2465466 , 0.19457218, 0.46703779,
       0.28676085, 0.24070067, 0.13883034, 0.37172668, 0.58291313,
       0.2483982 , 0.2483982 , 0.14388744, 0.27656714, 0.38150904,
       0.13210269, 0.42439063, 0.25436846, 0.26703827, 0.13210269,
       0.78909541, 0.47818866, 0.82340905, 0.74477271, 0.25625882,
       0.82340905, 0.39138847, 0.14909687, 0.3684951 , 0.39138847,
       0.27527272, 0.79594651, 0.79594651, 0.27527272, 0.79594651,
       0.26235206, 0.65517084, 0.39138847, 0.96891481, 0.752178  ,
       0.96891481, 0.752178  , 0.25593668, 0.74477271, 0.85998783,
       0.27527272, 0.752178  , 0.81292506, 0.15446087, 0.88807828,
       0.27049534, 0.59345377, 0.60551689, 0.75261221, 0.28366283,
       0.49900902, 0.40135771, 0.59345377, 0.75986339, 0.27049534,
       0.15446087, 0.59345377, 0.28366283, 0.40135771, 0.60551689,
       0.86493022, 0.52997332, 0.28366283, 0.80263072, 0.49900902,
       0.75544244, 0.41140922, 0.29220555, 0.57952086, 0.29220555,
       0.29220555, 0.89244858, 0.76982862, 0.54033854, 0.41970633,
       0.57952086, 0.29220555, 0.29220555, 0.29220555, 0.83544115,
       0.46566767, 0.46566767, 0.1528722 , 0.1528722 , 0.46566767,
       0.1528722 , 0.7621678 , 0.67895885, 0.09833694, 0.76248265,
       0.09833694, 0.19642418, 0.88993892, 0.19642418, 0.19642418,
       0.67065936, 0.21393279, 0.81485057, 0.20308448, 0.21393279,
       0.20308448, 0.10209388, 0.20218443, 0.20308448, 0.32285914,
       0.20308448, 0.68501484, 0.20308448, 0.20308448, 0.21393279,
       0.476049  , 0.15834675, 0.20308448, 0.24534259, 0.10209388,
       0.20308448, 0.67065936, 0.20308448, 0.22214099, 0.207392  ,
       0.20308448, 0.68501484, 0.20308448, 0.35515542, 0.21393279,
       0.20308448, 0.20308448, 0.207392  , 0.20991163, 0.36475487,
       0.15082727, 0.36475487, 0.58665832, 0.20991163, 0.22102348,
       0.20991163, 0.22102348, 0.10597748, 0.214325  , 0.89320731,
       0.67979659, 0.20991163, 0.20991163, 0.10597748, 0.67979659,
       0.82105476, 0.20991163, 0.69393555, 0.20991163, 0.52377177,
       0.15082727, 0.20991163, 0.36475487, 0.20991163, 0.10597748,
       0.20991163, 0.20991163, 0.13020038, 0.70406498, 0.20991163,
       0.20991163, 0.48645108, 0.92800225, 0.74449629, 0.70271326,
       0.52163219, 0.89711735, 0.87524189, 0.68159008, 0.10999072,
       0.96043474, 0.26455848, 0.13229726, 0.42662297, 0.52163219,
       0.25391465, 0.10999072, 0.77612   , 0.33346697, 0.10999072,
       0.23687375, 0.77612   , 0.54921452, 0.10999072, 0.26188901,
       0.77092623, 0.2286918 , 0.53201893, 0.46755235, 0.50728146,
       0.34302973, 0.69648251, 0.89118928, 0.22309993, 0.11413653,
       0.13715429, 0.5595081 , 0.12454854, 0.13715429, 0.11413653,
       0.39130775, 0.27274492, 0.72112877, 0.70319994, 0.34302973,
       0.63011722, 0.71134395, 0.86071602, 0.2286918 , 0.34302973])

In [43]:
data_to_load_in_tableau['Probability_of_excessivly_absent'] = Probability_of_excessivly_absent

In [44]:
data_to_load_in_tableau

,Reason_1,Reason_2,Reason_3,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability_of_excessivly_absent
0,0,0,0,7,289,33,30,0,2,1,0.565087
1,0,0,0,7,118,50,31,0,1,0,0.147318
2,0,0,0,7,179,38,31,0,0,0,0.238888
3,1,0,0,7,279,39,24,0,2,0,0.871080
4,0,0,0,7,289,33,30,0,2,1,0.565087
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,5,179,40,22,1,2,0,0.630117
696,1,0,0,5,225,28,24,0,1,2,0.711344
697,1,0,0,5,330,28,25,1,0,0,0.860716
698,0,0,0,5,235,32,25,1,0,0,0.228692
699,0,0,0,5,291,40,25,0,1,1,0.343030

In [45]:
data_to_load_in_tableau.to_csv('data_to_load_in_tableau.csv', index = False)